# Generated by Django 2.0.5 on 2018-05-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_text', models.CharField(blank=True, default='', max_length=200)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('state_of_domicile', models.CharField(max_length=2)),
                ('group_code_id', models.CharField(blank=True, default='', max_length=20)),
                ('group_name', models.CharField(blank=True, default='', max_length=100)),
                ('co_code', models.CharField(blank=True, default='', max_length=20)),
                ('short_company_name', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('fein', models.CharField(blank=True, default='', max_length=20)),
                ('request_filing', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'contacts',
            },
        ),
    ]
